# Generated by Django 5.1.2 on 2024-11-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_alter_paymentdetail_exp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
