# Generated by Django 5.1.2 on 2024-11-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_reservation_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mark_not_active',
            field=models.BooleanField(default=False),
        ),
    ]
