# Generated by Django 5.1.2 on 2024-11-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_room_mark_not_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
